import { JSONContent } from '../../../../models/Characters';
import { RacaPayload } from '../../../../services/racasService';
import { CidadePayload } from '../../../../services/cidadesService';

export interface CharacterRoleplayFormProps {
  theme: 'dark' | 'light';
  neon: 'on' | 'off';
  userName: string;
  setUserName: (value: string) => void;
  race: number | undefined;
  setRace: (value: number) => void;
  city: number | undefined;
  setCity: (value: number) => void;
  selectedRace?: RacaPayload;
  listRaces: RacaPayload[];
  listCities: CidadePayload[];
  loadingRaces: boolean;
  loadingCities: boolean;
  avatarUrl: string;
  setAvatarUrl: (value: string) => void;
  setAvatarFile: (file: File | null) => void;
  galeriaUrls: string[];
  galeriaShapes?: string[];
  galeriaCaptions?: string[];
  onAddGaleria: (files: File[], shapes: string[]) => void;
  onRemoveGaleria: (index: number) => void;
  onGaleriaCaptionChange?: (index: number, caption: string) => void;
  history: JSONContent | string;
  setHistory: (value: JSONContent | string) => void;
  alignment: string;
  setAlignment: (value: string) => void;
  traits: string[];
  setTraits: (value: string[]) => void;
  nanites: string;
  setNanites: (value: string) => void;
  idpassiva?: number;
  setIdpassiva: (value: number | undefined) => void;
  ultimate: string;
  setUltimate: (value: string) => void;
  costumes: string;
  setCostumes: (value: string) => void;
  extraInformation: string;
  setExtraInformation: (value: string) => void;
  visivel?: boolean;
  setVisivel?: (value: boolean) => void;
  destaque?: boolean;
  setDestaque?: (value: boolean) => void;
  listPersonagemRelacionado: { id: number; nome: string }[];
  setListPersonagemRelacionado: React.Dispatch<React.SetStateAction<{ id: number; nome: string }[]>>;
  personagens: any[];
  allPersonagens: any[];
  searchTerm: string;
  loadingPersonagens: boolean;
  searchPersonagens: (query: string) => void;
  raceChangeMode?: 'default' | 'current-or-android' | 'all';
  nameError?: boolean;
  nameErrorMessage?: string;
  onNameFocus?: () => void;
  raceError?: boolean;
  raceErrorMessage?: string;
  onRaceFocus?: () => void;
}
