import { Item } from '../../../../../../models/Itens';
import { Skills } from '../../../../../../models/Skills';
import { Magia } from '../../../../../../models/Magias';
import { RacaPayload } from '../../../../../../services/racasService';
import { CidadePayload } from '../../../../../../services/cidadesService';
import { personagensMock } from '../../../../../../Mock/characters.mock';

export interface BasicInfoFormProps {
  theme: 'dark' | 'light';
  neon: 'on' | 'off';
  userName: string;
  setUserName: (value: string) => void;
  race: number | undefined;
  setRace: (value: number) => void;
  city: number | undefined;
  setCity: (value: number) => void;
  avatarUrl: string;
  setAvatarUrl: (value: string) => void;
  setAvatarFile: (file: File | null) => void;
  history: string;
  setHistory: (value: string) => void;
  costumes: string;
  setCostumes: (value: string) => void;
  extraInformation: string;
  setExtraInformation: (value: string) => void;
  nanites: string;
  setNanites: (value: string) => void;
  alignment: string;
  setAlignment: (value: string) => void;
  traits: string[];
  setTraits: (value: string[]) => void;
  itens: Item[];
  setItens: (value: Item[]) => void;
  skills: Skills[];
  setSkills: (value: Skills[]) => void;
  magias: Magia[];
  setMagias: (value: Magia[]) => void;
  listPersonagemRelacionado: { id: number; nome: string }[];
  setListPersonagemRelacionado: React.Dispatch<React.SetStateAction<{ id: number; nome: string }[]>>;
  statusBasico: {
    vida: number;
    estamina: number;
    mana: number;
    capacidadeCarga: number;
  };
  setStatusBasico: React.Dispatch<React.SetStateAction<{
    vida: number;
    estamina: number;
    mana: number;
    capacidadeCarga: number;
  }>>;
  errors: { name?: string; race?: string };
  userError: boolean;
  setUserError: (value: boolean) => void;
  raceError: boolean;
  setRaceError: (value: boolean) => void;
  listCities: CidadePayload[];
  loadingCities: boolean;
  listRaces: RacaPayload[];
  loadingRaces: boolean;
  selectedRace: RacaPayload | undefined;
  personagens: typeof personagensMock;
  allPersonagens: typeof personagensMock;
  searchTerm: string;
  loadingPersonagens: boolean;
  searchPersonagens: (query: string) => void;
  listItens: Item[];
  handleSelectItem: (item: Item) => void;
  itemColumns: any;
  skillsColumns: any;
  magiasColumns: any;
}
