// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdisseiaWiki.Data;

#nullable disable

namespace OdisseiaWiki.Migrations
{
    [DbContext(typeof(OdisseiaContext))]
    [Migration("20260720224445_AdicionarDetalhesRacas")]
    partial class AdicionarDetalhesRacas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<string>("Iditem")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IDItem");

                    b.Property<string>("AtributosJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Efeito")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IditemBase")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Idpersonagem")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PersonagemIdpersonagem")
                        .HasColumnType("int(11)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Tipo");

                    b.Property<bool>("Visivel")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Iditem")
                        .HasName("PRIMARY");

                    b.HasIndex("PersonagemIdpersonagem");

                    b.ToTable("itens", (string)null);
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Cidade", b =>
                {
                    b.Property<int>("Idcidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("IDCidade");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idcidade"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GaleriaImagem")
                        .HasColumnType("longtext");

                    b.Property<string>("Imagem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PontosDeInteresse")
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<bool>("Visivel")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Idcidade")
                        .HasName("PRIMARY");

                    b.ToTable("cidades", (string)null);
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Infolore", b =>
                {
                    b.Property<int>("IdinfoLore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("IDInfoLore");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdinfoLore"));

                    b.Property<string>("Conteudo")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Visivel")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdinfoLore")
                        .HasName("PRIMARY");

                    b.ToTable("infolore", (string)null);
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Mesa", b =>
                {
                    b.Property<int>("Idmesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("IDMesa");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idmesa"));

                    b.Property<string>("CodigoSistema")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdusuarioCriacao")
                        .HasColumnType("int(11)")
                        .HasColumnName("IDUsuarioCriacao");

                    b.Property<string>("Imagem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("PadraoSistema")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Idmesa")
                        .HasName("PRIMARY");

                    b.HasIndex("CodigoSistema")
                        .IsUnique()
                        .HasDatabaseName("UX_Mesa_CodigoSistema");

                    b.HasIndex(new[] { "IdusuarioCriacao" }, "ID usuario criacao");

                    b.ToTable("mesas", (string)null);
                });

            modelBuilder.Entity("OdisseiaWiki.Models.MesaEntidadeConfig", b =>
                {
                    b.Property<int>("IdmesaEntidadeConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("IDMesaEntidadeConfig");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdmesaEntidadeConfig"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Identidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Idmesa")
                        .HasColumnType("int(11)")
                        .HasColumnName("IDMesa");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdmesaEntidadeConfig")
                        .HasName("PRIMARY");

                    b.HasIndex("Idmesa", "TipoEntidade", "Identidade")
                        .IsUnique()
                        .HasDatabaseName("UX_MesaEntidadeConfig_Mesa_Tipo_Entidade");

                    b.ToTable("mesaentidadeconfig", (string)null);
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Mesausuario", b =>
                {
                    b.Property<int>("IdmesaUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("IDMesaUsuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdmesaUsuario"));

                    b.Property<int?>("Idmesa")
                        .HasColumnType("int(11)")
                        .HasColumnName("IDMesa");

                    b.Property<int?>("Idusuario")
                        .HasColumnType("int(11)")
                        .HasColumnName("IDUsuario");

                    b.HasKey("IdmesaUsuario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Idmesa" }, "ID mesa");

                    b.HasIndex(new[] { "Idusuario" }, "ID usuario");

                    b.ToTable("mesausuarios", (string)null);
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Page", b =>
                {
                    b.Property<int>("IdPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPage"));

                    b.Property<string>("CoverImage")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Visivel")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdPage");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.PageBlock", b =>
                {
                    b.Property<int>("IdPageBlock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPageBlock"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdPage")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdPageBlock");

                    b.HasIndex("IdPage");

                    b.ToTable("PageBlocks");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Passiva", b =>
                {
                    b.Property<int>("Idpassiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idpassiva"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<bool>("Visivel")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Idpassiva");

                    b.ToTable("Passivas");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Passivaraca", b =>
                {
                    b.Property<int>("IdpassivaRaca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdpassivaRaca"));

                    b.Property<int>("Idpassiva")
                        .HasColumnType("int");

                    b.Property<int>("Idraca")
                        .HasColumnType("int");

                    b.Property<int>("PassivaIdpassiva")
                        .HasColumnType("int");

                    b.Property<int>("RacaIdraca")
                        .HasColumnType("int(11)");

                    b.HasKey("IdpassivaRaca");

                    b.HasIndex("PassivaIdpassiva");

                    b.HasIndex("RacaIdraca");

                    b.ToTable("Passivaracas");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.PersonagemJogador", b =>
                {
                    b.Property<int>("IdpersonagemJogador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("IDPersonagemJogador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdpersonagemJogador"));

                    b.Property<string>("Alinhamento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Costumes")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GaleriaImagem")
                        .HasColumnType("longtext");

                    b.Property<string>("Historia")
                        .HasColumnType("text");

                    b.Property<int?>("Idcidade")
                        .HasColumnType("int(11)")
                        .HasColumnName("IDCidade");

                    b.Property<int>("Idmesa")
                        .HasColumnType("int(11)")
                        .HasColumnName("IDMesa");

                    b.Property<int?>("Idpassiva")
                        .HasColumnType("int");

                    b.Property<int>("Idraca")
                        .HasColumnType("int(11)")
                        .HasColumnName("IDRaca");

                    b.Property<int>("Idusuario")
                        .HasColumnType("int(11)")
                        .HasColumnName("IDUsuario");

                    b.Property<string>("Imagem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Implantes")
                        .HasColumnType("longtext");

                    b.Property<string>("InfoSecundariasJson")
                        .HasColumnType("text");

                    b.Property<string>("InventarioJson")
                        .HasColumnType("json");

                    b.Property<string>("Magia")
                        .HasColumnType("longtext");

                    b.Property<string>("Nanites")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PassivaIdpassiva")
                        .HasColumnType("int");

                    b.Property<string>("PersonagemsVinculados")
                        .HasColumnType("longtext");

                    b.Property<string>("Skills")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Tracos")
                        .HasColumnType("text");

                    b.Property<string>("Ultimate")
                        .HasColumnType("longtext");

                    b.HasKey("IdpersonagemJogador")
                        .HasName("PRIMARY");

                    b.HasIndex("PassivaIdpassiva");

                    b.HasIndex(new[] { "Idcidade" }, "ID_cidades");

                    b.HasIndex(new[] { "Idmesa" }, "ID_mesas");

                    b.HasIndex(new[] { "Idraca" }, "ID_racas");

                    b.HasIndex(new[] { "Idusuario" }, "ID_usuarios");

                    b.ToTable("personagensJogador", (string)null);
                });

            modelBuilder.Entity("OdisseiaWiki.Models.PersonagemProficiencia", b =>
                {
                    b.Property<int>("IdpersonagemProficiencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdpersonagemProficiencia"));

                    b.Property<int?>("Idpersonagem")
                        .HasColumnType("int");

                    b.Property<int?>("IdpersonagemJogador")
                        .HasColumnType("int");

                    b.Property<int>("Idproficiencia")
                        .HasColumnType("int");

                    b.Property<int?>("PersonagemIdpersonagem")
                        .HasColumnType("int(11)");

                    b.Property<int?>("PersonagemJogadorIdpersonagemJogador")
                        .HasColumnType("int(11)");

                    b.Property<int>("ProficienciaIdproficiencia")
                        .HasColumnType("int");

                    b.HasKey("IdpersonagemProficiencia");

                    b.HasIndex("PersonagemIdpersonagem");

                    b.HasIndex("PersonagemJogadorIdpersonagemJogador");

                    b.HasIndex("ProficienciaIdproficiencia");

                    b.ToTable("PersonagemProficiencias");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Personageminfolore", b =>
                {
                    b.Property<int>("IdpersonagemInfoLore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("IDPersonagemInfoLore");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdpersonagemInfoLore"));

                    b.Property<int>("IdinfoLore")
                        .HasColumnType("int(11)")
                        .HasColumnName("IDInfoLore");

                    b.Property<int>("Idpersonagem")
                        .HasColumnType("int(11)")
                        .HasColumnName("IDPersonagem");

                    b.HasKey("IdpersonagemInfoLore")
                        .HasName("PRIMARY");

                    b.ToTable("personageminfolore", (string)null);
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Personagen", b =>
                {
                    b.Property<int>("Idpersonagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("IDPersonagem");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idpersonagem"));

                    b.Property<string>("Alinhamento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Costumes")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GaleriaImagem")
                        .HasColumnType("longtext");

                    b.Property<string>("Historia")
                        .HasColumnType("longtext");

                    b.Property<int?>("Idcidade")
                        .HasColumnType("int(11)")
                        .HasColumnName("IDCidade");

                    b.Property<int?>("Idpassiva")
                        .HasColumnType("int");

                    b.Property<int>("Idraca")
                        .HasColumnType("int(11)")
                        .HasColumnName("IDRaca");

                    b.Property<string>("Imagem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Implantes")
                        .HasColumnType("longtext");

                    b.Property<string>("InventarioJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Magia")
                        .HasColumnType("longtext");

                    b.Property<string>("Nanites")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PassivaIdpassiva")
                        .HasColumnType("int");

                    b.Property<string>("PersonagemsVinculados")
                        .HasColumnType("longtext");

                    b.Property<string>("Skills")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Tracos")
                        .HasColumnType("text");

                    b.Property<string>("Ultimate")
                        .HasColumnType("longtext");

                    b.Property<bool>("Visivel")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Idpersonagem")
                        .HasName("PRIMARY");

                    b.HasIndex("PassivaIdpassiva");

                    b.HasIndex(new[] { "Idcidade" }, "ID cidades");

                    b.HasIndex(new[] { "Idraca" }, "ID racas");

                    b.ToTable("personagens", (string)null);
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Proficiencia", b =>
                {
                    b.Property<int>("Idproficiencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idproficiencia"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<bool>("Visivel")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Idproficiencia");

                    b.ToTable("Proficiencias");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Raca", b =>
                {
                    b.Property<int>("Idraca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("IDRaca");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idraca"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GaleriaImagem")
                        .HasColumnType("longtext");

                    b.Property<string>("Imagem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusJson")
                        .HasColumnType("json");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Variacoes")
                        .HasColumnType("longtext");

                    b.Property<bool>("Visivel")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Idraca")
                        .HasName("PRIMARY");

                    b.ToTable("racas", (string)null);
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Usuario", b =>
                {
                    b.Property<int>("Idusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("IDUsuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idusuario"));

                    b.Property<string>("Celular")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Idusuario")
                        .HasName("PRIMARY");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.HasOne("OdisseiaWiki.Models.Personagen", "Personagem")
                        .WithMany()
                        .HasForeignKey("PersonagemIdpersonagem");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Mesa", b =>
                {
                    b.HasOne("OdisseiaWiki.Models.Usuario", "IdusuarioCriacaoNavigation")
                        .WithMany("Mesas")
                        .HasForeignKey("IdusuarioCriacao")
                        .HasConstraintName("ID usuario criacao");

                    b.Navigation("IdusuarioCriacaoNavigation");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.MesaEntidadeConfig", b =>
                {
                    b.HasOne("OdisseiaWiki.Models.Mesa", "IdmesaNavigation")
                        .WithMany("MesaEntidadeConfigs")
                        .HasForeignKey("Idmesa")
                        .IsRequired()
                        .HasConstraintName("FK_MesaEntidadeConfig_Mesa");

                    b.Navigation("IdmesaNavigation");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Mesausuario", b =>
                {
                    b.HasOne("OdisseiaWiki.Models.Mesa", "IdmesaNavigation")
                        .WithMany("Mesausuarios")
                        .HasForeignKey("Idmesa")
                        .HasConstraintName("ID mesa");

                    b.HasOne("OdisseiaWiki.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Mesausuarios")
                        .HasForeignKey("Idusuario")
                        .HasConstraintName("ID usuario");

                    b.Navigation("IdmesaNavigation");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.PageBlock", b =>
                {
                    b.HasOne("OdisseiaWiki.Models.Page", "Page")
                        .WithMany("Blocks")
                        .HasForeignKey("IdPage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Passivaraca", b =>
                {
                    b.HasOne("OdisseiaWiki.Models.Passiva", "Passiva")
                        .WithMany("Passivaracas")
                        .HasForeignKey("PassivaIdpassiva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OdisseiaWiki.Models.Raca", "Raca")
                        .WithMany()
                        .HasForeignKey("RacaIdraca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passiva");

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.PersonagemJogador", b =>
                {
                    b.HasOne("OdisseiaWiki.Models.Cidade", "IdcidadeNavigation")
                        .WithMany()
                        .HasForeignKey("Idcidade")
                        .HasConstraintName("FK_PersonagensJogador_Cidade");

                    b.HasOne("OdisseiaWiki.Models.Mesa", "Mesa")
                        .WithMany("PersonagensJogadores")
                        .HasForeignKey("Idmesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PersonagensJogador_Mesa");

                    b.HasOne("OdisseiaWiki.Models.Raca", "IdracaNavigation")
                        .WithMany()
                        .HasForeignKey("Idraca")
                        .IsRequired()
                        .HasConstraintName("FK_PersonagensJogador_Raca");

                    b.HasOne("OdisseiaWiki.Models.Usuario", "Usuario")
                        .WithMany("PersonagensJogadores")
                        .HasForeignKey("Idusuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PersonagensJogador_Usuario");

                    b.HasOne("OdisseiaWiki.Models.Passiva", "Passiva")
                        .WithMany("PersonagensJogadores")
                        .HasForeignKey("PassivaIdpassiva");

                    b.Navigation("IdcidadeNavigation");

                    b.Navigation("IdracaNavigation");

                    b.Navigation("Mesa");

                    b.Navigation("Passiva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.PersonagemProficiencia", b =>
                {
                    b.HasOne("OdisseiaWiki.Models.Personagen", "Personagem")
                        .WithMany("PersonagemProficiencias")
                        .HasForeignKey("PersonagemIdpersonagem");

                    b.HasOne("OdisseiaWiki.Models.PersonagemJogador", "PersonagemJogador")
                        .WithMany("PersonagemProficiencias")
                        .HasForeignKey("PersonagemJogadorIdpersonagemJogador");

                    b.HasOne("OdisseiaWiki.Models.Proficiencia", "Proficiencia")
                        .WithMany("Personagens")
                        .HasForeignKey("ProficienciaIdproficiencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");

                    b.Navigation("PersonagemJogador");

                    b.Navigation("Proficiencia");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Personagen", b =>
                {
                    b.HasOne("OdisseiaWiki.Models.Cidade", "IdcidadeNavigation")
                        .WithMany("Personagens")
                        .HasForeignKey("Idcidade")
                        .HasConstraintName("ID cidades");

                    b.HasOne("OdisseiaWiki.Models.Raca", "IdracaNavigation")
                        .WithMany("Personagens")
                        .HasForeignKey("Idraca")
                        .IsRequired()
                        .HasConstraintName("ID racas");

                    b.HasOne("OdisseiaWiki.Models.Passiva", "Passiva")
                        .WithMany("Personagens")
                        .HasForeignKey("PassivaIdpassiva");

                    b.Navigation("IdcidadeNavigation");

                    b.Navigation("IdracaNavigation");

                    b.Navigation("Passiva");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Cidade", b =>
                {
                    b.Navigation("Personagens");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Mesa", b =>
                {
                    b.Navigation("MesaEntidadeConfigs");

                    b.Navigation("Mesausuarios");

                    b.Navigation("PersonagensJogadores");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Page", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Passiva", b =>
                {
                    b.Navigation("Passivaracas");

                    b.Navigation("Personagens");

                    b.Navigation("PersonagensJogadores");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.PersonagemJogador", b =>
                {
                    b.Navigation("PersonagemProficiencias");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Personagen", b =>
                {
                    b.Navigation("PersonagemProficiencias");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Proficiencia", b =>
                {
                    b.Navigation("Personagens");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Raca", b =>
                {
                    b.Navigation("Personagens");
                });

            modelBuilder.Entity("OdisseiaWiki.Models.Usuario", b =>
                {
                    b.Navigation("Mesas");

                    b.Navigation("Mesausuarios");

                    b.Navigation("PersonagensJogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
