import { Item } from '../../../../models/Itens';
import { Magia } from '../../../../models/Magias';
import { Skills } from '../../../../models/Skills';
import { Principais, Secundarios } from '../../../Hub/UserCharacters/CharacterCreate/FormUserCharacter/FormUserCharacter.type';
import { RacaPayload } from '../../../../services/racasService';
import { Defesas, StatusBase } from '../../../../models/Characters';
import { SistemaRuntimeContexto } from '../../../../models/SistemaRpg';
import { CharacterComparisonSource } from '../../../../components/CharacterComparison';

export interface CharacterSystemFormProps {
  theme: 'dark' | 'light';
  neon: 'on' | 'off';
  allowMaxStatusEditing?: boolean;
  userName: string;
  selectedRace?: RacaPayload;
  raceImageUrl: string;
  avatarUrl: string;
  xp: number;
  setXp: (value: number) => void;
  level: number;
  setLevel: (value: number) => void;
  statusBasico: StatusBase;
  setStatusBasico: React.Dispatch<React.SetStateAction<StatusBase>>;
  atributosPrincipais: Principais;
  setAtributosPrincipais: (value: Principais) => void;
  atributosSecundarios: Secundarios;
  setAtributosSecundarios: (value: Secundarios) => void;
  defesas: Defesas;
  setDefesas: (value: Defesas) => void;
  itens: Item[];
  setItens: (value: Item[]) => void;
  skills: Skills[];
  setSkills: (value: Skills[]) => void;
  magias: Magia[];
  setMagias: (value: Magia[]) => void;
  listItens: Item[];
  handleSelectItem: (item: Item) => void;
  itemColumns: any;
  skillsColumns: any;
  magiasColumns: any;
  runtimeContext?: SistemaRuntimeContexto | null;
  comparisonSource?: CharacterComparisonSource;
  comparisonId?: number;
  comparisonTableId?: number | null;
  comparisonTableName?: string | null;
}
